name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        #os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-14]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: latest

      - name: build wheels
        run: poetry build

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.whl
